name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  notification-templates:
    uses: vpsfreecz/vpsadmin/.github/workflows/notification-templates.yml@f2f7c6a9a10437892929fdf99b968e1010aa19b0
